### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by geigerzaehler** [geigerzaehler/beets-alternatives#23]
Publish this code as a package to PyPI. Setup CI to do auto-publishing.

**Comment by wisp3rwind** [comment]
From my side, now could be the time :) All changes from my fork will be backported when #26 and #27 are merged.

Thanks again for all of the reviews and the nagging about adding tests, the quality of all of those patches has certainly improved a lot!

**Comment by wisp3rwind** [comment]
@Profpatsch (I hope you're the one to bug, or at least can ping someone else), I just noticed that you switched the NixOS package to my repository. Would you please switch it back to this repo soon-ish? The code here is better tested, and #27 is handled less elegantly on my fork since it requires changes to the configuration. The latter are undocumented, but whoever has bothered to take a look at the code might end up with (harmless) unused config entries.

**Comment by geigerzaehler** [comment]
It on [PyPI](https://pypi.org/project/beets-alternatives/) now.

**Comment by wisp3rwind** [comment]
@aszlig: see above, I hadn't noticed that the maintainers for the `beets` package changed in the meantime. Thanks!

**Comment by aszlig** [comment]
@wisp3rwind: Thanks for the heads-up, will change that. Yes, @Profpatsch has removed himself from the main beets package in NixOS/nixpkgs@2922bee722e501cbc1c19dfccd74930a6b2dc35c, but when it comes to beets-alternatives I was the one introducing it in nixpkgs and also maintaining it since.

**Comment by aszlig** [comment]
@wisp3rwind: See NixOS/nixpkgs@887ae75eb22e1929f406adf5bdba5e8d25453755. I also added myself as the maintainer in NixOS/nixpkgs@bef2a439576b38e69aed756fe8e43bd4f7869723 to avoid such confusion in the future. Thanks :-)
